config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  root to: "events#index"
  get 'static_pages/index'
  get 'static_pages/secret'
  devise_for :users

  resources :events
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    after_create :attend_event_send

    def attend_event_send
        UserMailer.attend_event_email(User.find(self.user_id).email).deliver_now
    end

    belongs_to :event
    belongs_to :user

end

app/models/event.rb
class Event < ApplicationRecord
    has_many :attendances
    has_many :users, through: :attendances

    validates :start_date, presence: true
    validate :start_date_cannot_be_in_the_past
    validates :duration, presence: true
    validate :duration_validate
    validates :title, presence: true, length: {in: 5..140}
    validates :description, presence: true, length: {in: 20..1000}
    validates :price, inclusion: { in: 1..1000 }
    validates :location, presence: true




    def start_date_cannot_be_in_the_past
      if start_date.present? && start_date < Date.today
        errors.add(:start_date, "Start date is not valid (did you input a passed date?)")
      end
    end  
    def duration_validate
        if duration.present? && (duration%5 != 0 || duration <= 0)
            errors.add(:duration, "Duration must be a multiple of 5 and strictly higher than 0")
        end
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send

    has_many :attendances
    has_many :events, through: :attendances

    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
  end

  def show
    @event = Event.find(params[:id])
    @title = @event.title
    @description = @event.description
    @price = @event.price
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  
  def index
  end

  def secret
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = current_user
    @email = @user.email
    @fname = @user.first_name
    @lname = @user.last_name
    if @fname == nil
      @fname = "first name"
    end
    if @lname == nil
      @lname = "last name"
    end

   @user_created_events = Event.where(admin_email: @email)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<main role="main">

<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1 class="display-3">Welcome to Nextevent</h1>
    <p>Nextevent is the best place to organize, share and find attendees to your next business event.</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Create an event &raquo;</a></p>
  </div>
</div>

<div class="container">
  <div class="row">
    <% @events.each do |event| %>
      <div class="col-md-4">
        <h2><%= event.title %></h2>
        <p> <%= event.description%> </p>
        <p><a class="btn btn-secondary" href="<%=event_path(event.id)%>" role="button">View details</a></p>
      </div>
    <%end%>
  </div>

  <hr>

</div> <!-- /container -->

</main>

app/views/events/new.html.erb
<h1>Create new event page</h1>

app/views/events/show.html.erb
<div class="card text-center">
  <div class="card-header">
  </div>
  <div class="card-body">
    <br>
    <div class="container">
    <div class="card-deck mb-3 text-center">
      <div class="mb-4">
      </div>
      <div class="card mb-4 box-shadow">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal"><%=@title%></h4>
        </div>
        <div class="card-body">
          <h1 class="card-title pricing-card-title">$<%=@price%></h1>
          <h4><%=@description%></h4>
          <button type="button" class="btn btn-lg btn-block btn-primary">I want to attend</button>
        </div>
      </div>

      <div class="mb-4"></div>
      
    </div>

  </div>
  <div class="card-footer text-muted">
    Date of the event : <%=@event.start_date%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventPlannerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="<%=events_path%>">Next Event</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="<%=events_path%>">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="#">Create Event<span class="sr-only">(current)</span></a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown my-2 my-lg-0">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              User
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="<%=user_path(current_user.id)%>">My Profile</a>
              <a class="dropdown-item" data-method="delete" href="<%=destroy_user_session_path%>">Log out</a>
            </div>
          </li>
        <%else%>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_session_path%>">Log in</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=new_user_registration_path%>">Sign Up</a>
          </li>
        <%end%>
        
      </ul>
    </div>
  </nav>
</header>

    <%= yield %>
  </body>
</html>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>